/**
 * AVTOMATIK GENERATSIYA QILINGAN — QO'LDA TAHRIRLAMANG.
 *
 * Manba: learning-center-saas/src ichidagi barcha controller fayllar
 * (`@RequirePermissions(...)` dekoratorlari).
 * Qayta generatsiya: npm run gen:api-permissions
 *
 * Jadvalda backenddagi BARCHA endpointlar bor. `permissions: []` — endpoint
 * ochiq. Ochiq endpointlar ham ro'yxatda turadi, chunki ular parametrli
 * qoidani to'sishi kerak ('/centers/all' ochiq, '/centers/:id' esa emas).
 * Ro'yxatda umuman yo'q manzil — tekshirilmaydi (default: ochiq).
 */

export interface ApiPermissionRule {
  method: string
  /** Nest shabloni, masalan '/subjects/:id' */
  path: string
  /** Bittasi yetarli (OR) — backenddagi PermissionsGuard bilan bir xil */
  permissions: string[]
  /**
   * Endpoint `centerId` filtrini qabul qiladi. `baseHttp.ts` bunday
   * so'rovlarga header'da tanlangan aktiv filialni avtomatik qo'shadi.
   */
  acceptsCenterId?: boolean
}

export const API_PERMISSION_RULES: ApiPermissionRule[] = [
  { method: 'POST', path: '/auth/login', permissions: [] },
  { method: 'POST', path: '/auth/logout', permissions: [] },
  { method: 'GET', path: '/auth/me', permissions: [] },
  { method: 'POST', path: '/auth/register', permissions: [] },
  { method: 'GET', path: '/centers', permissions: ['centers.view'] },
  { method: 'POST', path: '/centers', permissions: ['centers.manage'] },
  { method: 'DELETE', path: '/centers/:id', permissions: ['centers.manage'] },
  { method: 'GET', path: '/centers/:id', permissions: ['centers.view'] },
  { method: 'PUT', path: '/centers/:id', permissions: ['centers.manage'] },
  { method: 'POST', path: '/centers/:id/capture-ip', permissions: ['centers.manage'] },
  { method: 'GET', path: '/centers/all', permissions: [] },
  { method: 'GET', path: '/expenses', permissions: ['expenses.view'], acceptsCenterId: true },
  { method: 'POST', path: '/expenses', permissions: ['expenses.create'] },
  { method: 'DELETE', path: '/expenses/:id', permissions: ['expenses.delete'] },
  { method: 'GET', path: '/expenses/:id', permissions: ['expenses.view'] },
  { method: 'PUT', path: '/expenses/:id', permissions: ['expenses.update'] },
  { method: 'GET', path: '/group-schedule', permissions: ['schedule.view'] },
  { method: 'POST', path: '/group-schedule', permissions: ['schedule.manage'] },
  { method: 'DELETE', path: '/group-schedule/:id', permissions: ['schedule.manage'] },
  { method: 'GET', path: '/group-schedule/:id', permissions: ['schedule.view'] },
  { method: 'PUT', path: '/group-schedule/:id', permissions: ['schedule.manage'] },
  { method: 'GET', path: '/group-schedule/board', permissions: ['schedule.view'], acceptsCenterId: true },
  { method: 'POST', path: '/group-schedule/conflicts', permissions: ['schedule.view', 'groups.create', 'groups.update'] },
  { method: 'GET', path: '/group/all', permissions: ['groups.view'], acceptsCenterId: true },
  { method: 'GET', path: '/groups', permissions: ['groups.view'], acceptsCenterId: true },
  { method: 'POST', path: '/groups', permissions: ['groups.create'] },
  { method: 'GET', path: '/groups/:groupId/attendance', permissions: ['attendance.view'] },
  { method: 'GET', path: '/groups/:groupId/attendance/lesson-dates', permissions: ['attendance.view'] },
  { method: 'POST', path: '/groups/:groupId/attendance/reschedule', permissions: ['attendance.manage'] },
  { method: 'POST', path: '/groups/:groupId/attendance/submit', permissions: ['attendance.manage'] },
  { method: 'GET', path: '/groups/:groupId/plan', permissions: ['groupPlan.view'] },
  { method: 'POST', path: '/groups/:groupId/plan/distribute', permissions: ['groupPlan.manage'] },
  { method: 'PUT', path: '/groups/:groupId/plan/lessons/:lessonNumber/topics', permissions: ['groupPlan.manage'] },
  { method: 'PUT', path: '/groups/:groupId/plan/syllabus', permissions: ['groupPlan.attach'] },
  { method: 'DELETE', path: '/groups/:id', permissions: ['groups.delete'] },
  { method: 'GET', path: '/groups/:id', permissions: ['groups.view'] },
  { method: 'PUT', path: '/groups/:id', permissions: ['groups.update'] },
  { method: 'GET', path: '/groups/all', permissions: ['groups.view'], acceptsCenterId: true },
  { method: 'PUT', path: '/groups/change-status/:id', permissions: ['groups.changeStatus'] },
  { method: 'GET', path: '/leads', permissions: ['leads.view'], acceptsCenterId: true },
  { method: 'POST', path: '/leads', permissions: ['leads.create'] },
  { method: 'DELETE', path: '/leads/:id', permissions: ['leads.delete'] },
  { method: 'PUT', path: '/leads/:id', permissions: ['leads.update'] },
  { method: 'POST', path: '/leads/:id/transfer-to-student', permissions: ['leads.transfer'] },
  { method: 'PUT', path: '/leads/change-status/:id', permissions: ['leads.update'] },
  { method: 'GET', path: '/organizations/:id', permissions: [] },
  { method: 'GET', path: '/payments', permissions: ['payments.view'], acceptsCenterId: true },
  { method: 'GET', path: '/payments/:id', permissions: ['payments.view'] },
  { method: 'PUT', path: '/payments/:id', permissions: ['payments.update'] },
  { method: 'GET', path: '/payments/:paymentId/receipts', permissions: ['payments.view'] },
  { method: 'PUT', path: '/payments/apply-exclusion/:id', permissions: ['payments.exclusion'] },
  { method: 'PUT', path: '/payments/calculate/:id', permissions: ['payments.recalculate'] },
  { method: 'PUT', path: '/payments/confirm-receipt/:id', permissions: ['receipts.confirm'] },
  { method: 'PUT', path: '/payments/confirm-receipts', permissions: ['receipts.confirm'] },
  { method: 'GET', path: '/payments/export', permissions: ['payments.export'], acceptsCenterId: true },
  { method: 'PUT', path: '/payments/mark-as-paid/:id', permissions: ['payments.create'] },
  { method: 'PUT', path: '/payments/pay-debt/student/:studentId', permissions: ['payments.create'] },
  { method: 'PUT', path: '/payments/pay-partial/:id', permissions: ['payments.create'] },
  { method: 'GET', path: '/payments/pending-receipts', permissions: ['receipts.view'], acceptsCenterId: true },
  { method: 'PUT', path: '/payments/preview-exclusion/:id', permissions: ['payments.exclusion'] },
  { method: 'GET', path: '/payments/receipt/:receiptId/check', permissions: ['payments.view'] },
  { method: 'GET', path: '/payments/receipts-stats', permissions: ['receipts.view'], acceptsCenterId: true },
  { method: 'PUT', path: '/payments/reject-receipt/:id', permissions: ['receipts.reject'] },
  { method: 'GET', path: '/payments/student/:studentId/summary', permissions: ['payments.view'] },
  { method: 'GET', path: '/roles', permissions: ['roles.view'] },
  { method: 'POST', path: '/roles', permissions: ['roles.manage'] },
  { method: 'DELETE', path: '/roles/:id', permissions: ['roles.manage'] },
  { method: 'PUT', path: '/roles/:id', permissions: ['roles.manage'] },
  { method: 'GET', path: '/roles/permissions', permissions: ['roles.view'] },
  { method: 'GET', path: '/rooms', permissions: ['rooms.view'], acceptsCenterId: true },
  { method: 'POST', path: '/rooms', permissions: ['rooms.manage'] },
  { method: 'DELETE', path: '/rooms/:id', permissions: ['rooms.manage'] },
  { method: 'GET', path: '/rooms/:id', permissions: ['rooms.view'] },
  { method: 'PUT', path: '/rooms/:id', permissions: ['rooms.manage'] },
  { method: 'GET', path: '/staff-attendance', permissions: ['staffAttendance.view'], acceptsCenterId: true },
  { method: 'DELETE', path: '/staff-attendance/:id', permissions: ['staffAttendance.manage'] },
  { method: 'POST', path: '/staff-attendance/:id/confirm', permissions: ['staffAttendance.manage'] },
  { method: 'POST', path: '/staff-attendance/check-in', permissions: ['staffAttendance.checkIn'] },
  { method: 'POST', path: '/staff-attendance/manual', permissions: ['staffAttendance.manage'] },
  { method: 'GET', path: '/staff-attendance/me', permissions: ['staffAttendance.viewOwn'], acceptsCenterId: true },
  { method: 'GET', path: '/staff-attendance/me/today', permissions: ['staffAttendance.viewOwn'] },
  { method: 'GET', path: '/staff-attendance/report', permissions: ['staffAttendance.view'], acceptsCenterId: true },
  { method: 'GET', path: '/staff-salaries', permissions: ['payroll.view'], acceptsCenterId: true },
  { method: 'PUT', path: '/staff-salaries/pay/:id', permissions: ['payroll.pay'] },
  { method: 'GET', path: '/staff/:userId/deductions', permissions: ['staffPerformance.view'] },
  { method: 'GET', path: '/staff/:userId/overview', permissions: ['staffPerformance.view', 'staffAttendance.viewOwn'] },
  { method: 'POST', path: '/staff/deductions', permissions: ['payroll.deduct'] },
  { method: 'DELETE', path: '/staff/deductions/:id', permissions: ['payroll.deduct'] },
  { method: 'GET', path: '/staff/me/overview', permissions: ['staffAttendance.viewOwn'] },
  { method: 'GET', path: '/statistics/dashboard', permissions: ['statistics.view'], acceptsCenterId: true },
  { method: 'GET', path: '/student', permissions: ['students.view'], acceptsCenterId: true },
  { method: 'GET', path: '/students', permissions: ['students.view'], acceptsCenterId: true },
  { method: 'POST', path: '/students', permissions: ['students.create'] },
  { method: 'GET', path: '/students/:id', permissions: ['students.view'] },
  { method: 'PUT', path: '/students/:id', permissions: ['students.update'] },
  { method: 'GET', path: '/students/:id/discount-periods', permissions: ['students.discounts'] },
  { method: 'POST', path: '/students/:id/discount-periods', permissions: ['students.discounts'] },
  { method: 'DELETE', path: '/students/:id/discount-periods/:periodId', permissions: ['students.discounts'] },
  { method: 'PUT', path: '/students/:id/discount-periods/:periodId', permissions: ['students.discounts'] },
  { method: 'GET', path: '/students/all', permissions: ['students.view'], acceptsCenterId: true },
  { method: 'PUT', path: '/students/change-status/:id', permissions: ['students.changeStatus'] },
  { method: 'GET', path: '/students/referrals', permissions: ['students.view'] },
  { method: 'POST', path: '/students/transfer', permissions: ['students.transfer'] },
  { method: 'POST', path: '/students/transfer/preview', permissions: ['students.transfer'] },
  { method: 'GET', path: '/subjects', permissions: ['subjects.view'], acceptsCenterId: true },
  { method: 'POST', path: '/subjects', permissions: ['subjects.manage'] },
  { method: 'DELETE', path: '/subjects/:id', permissions: ['subjects.manage'] },
  { method: 'GET', path: '/subjects/:id', permissions: ['subjects.view'] },
  { method: 'PUT', path: '/subjects/:id', permissions: ['subjects.manage'] },
  { method: 'GET', path: '/subscriptions/organization/:id', permissions: [] },
  { method: 'GET', path: '/syllabuses', permissions: ['syllabus.view'], acceptsCenterId: true },
  { method: 'POST', path: '/syllabuses', permissions: ['syllabus.manage'] },
  { method: 'DELETE', path: '/syllabuses/:id', permissions: ['syllabus.manage'] },
  { method: 'GET', path: '/syllabuses/:id', permissions: ['syllabus.view'] },
  { method: 'PUT', path: '/syllabuses/:id', permissions: ['syllabus.manage'] },
  { method: 'POST', path: '/syllabuses/:id/topics', permissions: ['syllabus.manage'] },
  { method: 'DELETE', path: '/syllabuses/:id/topics/:topicId', permissions: ['syllabus.manage'] },
  { method: 'PUT', path: '/syllabuses/:id/topics/:topicId', permissions: ['syllabus.manage'] },
  { method: 'POST', path: '/syllabuses/:id/topics/:topicId/generate-content', permissions: ['syllabus.ai'] },
  { method: 'PUT', path: '/syllabuses/:id/topics/reorder', permissions: ['syllabus.manage'] },
  { method: 'POST', path: '/syllabuses/ai/chat', permissions: ['syllabus.ai'] },
  { method: 'POST', path: '/syllabuses/ai/save', permissions: ['syllabus.ai'] },
  { method: 'GET', path: '/teacher-earnings', permissions: ['payroll.view'] },
  { method: 'POST', path: '/teacher-earnings/calculate', permissions: ['payroll.calculate'] },
  { method: 'GET', path: '/teachers/me/today', permissions: ['teacher.today'], acceptsCenterId: true },
  { method: 'GET', path: '/users', permissions: ['users.view'], acceptsCenterId: true },
  { method: 'POST', path: '/users', permissions: ['users.create'] },
  { method: 'DELETE', path: '/users/:id', permissions: ['users.delete'] },
  { method: 'GET', path: '/users/:id', permissions: ['users.view'] },
  { method: 'PUT', path: '/users/:id', permissions: ['users.update'] },
  { method: 'GET', path: '/users/email/:email', permissions: ['users.view'] },
  { method: 'GET', path: '/users/employees', permissions: ['users.view', 'groups.create', 'groups.update'], acceptsCenterId: true },
  { method: 'GET', path: '/users/me', permissions: [] },
  { method: 'PUT', path: '/users/me', permissions: [] },
  { method: 'GET', path: '/users/teachers', permissions: ['users.view', 'groups.view', 'students.view'], acceptsCenterId: true },
]
